# Generated by Django 3.2.4 on 2021-06-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210609_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
